/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Light mode colors (Material Design 3)
        "surface-bright": "#f9f9ff",
        "on-secondary": "#eaffe2",
        "primary-fixed": "#91c5ff",
        "primary-fixed-dim": "#73b8ff",
        "secondary-container": "#a3f69c",
        "on-tertiary-fixed": "#00443a",
        "secondary-fixed": "#a3f69c",
        "secondary": "#1c6d25",
        "surface-dim": "#c8dbff",
        "on-surface-variant": "#4a6085",
        "on-tertiary-fixed-variant": "#006455",
        "primary-container": "#91c5ff",
        "surface-container-highest": "#d6e3ff",
        "background": "#f9f9ff",
        "error-dim": "#70030f",
        "on-secondary-fixed": "#004b0f",
        "surface-variant": "#d6e3ff",
        "secondary-fixed-dim": "#95e88f",
        "primary": "#0062a2",
        "error-container": "#f56965",
        "surface": "#f9f9ff",
        "on-error-container": "#65000b",
        "on-tertiary": "#e3fff6",
        "inverse-surface": "#030e20",
        "on-background": "#1b3355",
        "inverse-on-surface": "#929db4",
        "tertiary-fixed-dim": "#4fe5ca",
        "tertiary": "#006c5c",
        "secondary-dim": "#096119",
        "primary-dim": "#00568e",
        "outline": "#657ba2",
        "surface-container-low": "#f0f3ff",
        "tertiary-container": "#61f4d8",
        "outline-variant": "#9cb3dc",
        "surface-container-lowest": "#ffffff",
        "tertiary-dim": "#005e51",
        "on-primary-container": "#003f6a",
        "on-primary-fixed-variant": "#004878",
        "surface-tint": "#0062a2",
        "on-surface": "#1b3355",
        "error": "#ac3434",
        "inverse-primary": "#5eb0ff",
        "on-secondary-fixed-variant": "#176a21",
        "on-secondary-container": "#065f18",
        "on-tertiary-container": "#00594c",
        "tertiary-fixed": "#61f4d8",
        "on-primary": "#f7f9ff",
        "on-primary-fixed": "#002948",
        "on-error": "#fff7f6",
        "surface-container": "#e7eeff",
        "surface-container-high": "#dfe8ff",
      },
    },
  },
  plugins: [],
}
