services:
  - type: web
    name: merosadak-backend
    env: node
    nodeVersion: "20"
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RATE_LIMIT_MAX
        value: "100"
