name = "sadaksathi"
main = "backend/cloudflare/cf-worker.js"
compatibility_date = "2025-12-29"
account_id = "052a34d4627b5c02d0bff84ff1c0f906"
workers_dev = true

# Optional: Environment variables (only if you use them in Worker)
[vars]
FIREBASE_BACKEND = "https://sadaksathi.web.app"
RENDER_BACKEND = "" # put your render backend URL if you have one

# Cron job (runs every 5 minutes)
[triggers]
crons = ["*/5 * * * *"]